---
title: "Hospital Travelers Guide"
author: "Pedro Loes"
date: "2022-09-23"
runtime: shiny
output: 
  ioslides_presentation:
    logo: hospital_logo_map.png
---

## Overview

* __Hospital Travelers Guide__ is an application developed as a final project to the __Coursera John Hopkins Practical Data Science Specialization for the Data Products Course__.

* I'm currently working on a chatbot company as a data analyst. One of our clients is a travel insurance company. We implemented a network model to classify travelers needs based on text inputs between many categories and one of them is health insurance.

* The main purpose of the application is to guide the traveler to the __near hospitals__ based on their location coordinate shared with the bot on the __whatsapp__ channel.

* Repo: [GitHub](https://github.com/Protospi/Hospital-Travelers-Guide)

## Conversation Flow

1. Travelers start to talk with the chatbot and write their main reason to reach for insurance support.
2. A __Neural Network__ model predicts that the user wants information about nearby hospitals.
3. The bot asks for user location.
4. The application calculates distances from latitudes and longitudes against the hospitals database.
5. A world map is rendered on a __html__ page with the __traveler__ and the __3__ hospitals markers with name and addresses of the hospitals and also __3__ lines with the distances in kilometers.
6. A __url__ link is sent to the travelers on whatsapp so they can visualize the map on a __browser__.

## Data Source

* The dataset was retrieved through the download of a file in `.csv` format on the website below.

* [Geoplatform Opendata Arcgis](https://hifld-geoplatform.opendata.arcgis.com/datasets/6ac5e325468c4cb9b905f1728d6fbf0f_0/explore?location=36.946719%2C64.325615%2C4.00)

* This feature class/shapefile contains Hospitals derived from various sources for the [Homeland Infrastructure Foundation-Level Data](https://gii.dhs.gov/HIFLD)
  
* The database contains __7.623__ hospitals with features like names, addresses, latitudes and longitudes. It's not even __10%__ of the total hospitals in the world but the data is free and this project is just a prototype for a _minimum viable product_ that will go onto production if it's approved by stakeholders.

## Algorithm

1. Load the hospitals database, filter for _name_, _address_, _latitude_ and _longitude_.
2. Bind the rows with traveler coordinate data.
3. Calculate the euclidean distance between coordinates of the traveler and hospitals, arrange by distance and slice first __3__.
4. Transform the coordinate to the projection __+init=epsg:4326__ and calculate the distance in kilometers.
5. Draw the leaflet map plot in html web shiny reactive environment with the following elements:
6. Overlay markers for the traveler and __3__ nears hospital with hover tooltip containing the name and address of the hospitals. Lines between the traveler and the __3__ hospitals with hover tooltip showing the distance in kilometers. 

## Demo


```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Load libraries
library(leaflet)
library(shiny)
library(sf)
library(maptools)
library(dplyr)
library(tidyverse)
library(htmltools)

# Read data from hospitals
hospitals <- read_csv("final_project.csv") %>% 
  mutate(NAME = paste(NAME, ADDRESS, sep = "<br>")) %>% 
  select(NAME, LATITUDE, LONGITUDE)

# Define row
inputPanel(

# Define inputs
numericInput("lat",
             label = "Latitude",
             value = 38.897957,
             min = -90,
             max = 90),

numericInput("long",
             label = "Longitude",
             value = -77.036560,
             min = -180,
             max = 180)
)

# Define função para calculo da distancia euclidiana
dist_euc <- function(vect1, vect2) sqrt(sum((vect1 - vect2)^2))

# Define hospital icons
icons_hosp <- awesomeIcons(
  icon = 'hospital-o',
  lib = 'fa',
  iconColor = "#FFFFFF",
  markerColor = "red")

# Define user icons
icons_user <- awesomeIcons(
  icon = 'user',
  lib = 'fa',
  iconColor = "#FFFFFF",
  markerColor = "black")
  
# Render Plot
leaflet::renderLeaflet({
  
  # Define data frame
  df <- data.frame(NAME = c("Traveler"),
                   LATITUDE = input$lat,
                   LONGITUDE = input$long) %>% 
      bind_rows(hospitals) %>% 
      rowwise() %>%
      mutate(diff = dist_euc(c(input$lat, input$long),
                             c(LATITUDE, LONGITUDE))) %>% 
  arrange(diff) %>% 
  as_tibble() %>% 
  slice(1:4) 
  
  # Define df geo
  df_geo <- df
  
  # Define traveler
  df_tra <- data.frame(NAME = c("Traveler"),
                   LATITUDE = input$lat,
                   LONGITUDE = input$long)
  
  # Calculate Distances
  coordinates(df_geo) <- c('LONGITUDE', 'LATITUDE')
  proj4string(df_geo) <- CRS("+init=epsg:4326")
  distance <- df_geo %>% st_as_sf() %>% st_distance 
  dists <- round(as.numeric(distance[1,2:4]) / 1000,1)
  
  # LIst of labels
  labs <- as.list(df[2:4,]$NAME)
  user <- HTML(df[1,]$NAME)
  
  # Draw plot
  leaflet(df[2:4,]) %>% 
    addTiles() %>%
    addAwesomeMarkers(~LONGITUDE, ~LATITUDE, label = lapply(labs, HTML), icon = icons_hosp) %>% 
    addAwesomeMarkers(data = df_tra, ~LONGITUDE, ~LATITUDE, label = user, icon = icons_user) %>% 
    addPolylines(data=df[c(1,2),], ~LONGITUDE, ~LATITUDE, label = paste0("Distance: ", dists[1], " km"))%>% 
    addPolylines(data=df[c(1,3),], ~LONGITUDE, ~LATITUDE, label = paste0("Distance: ", dists[2], " km"))%>% 
    addPolylines(data=df[c(1,4),], ~LONGITUDE, ~LATITUDE, label = paste0("Distance: ", dists[3], " km"))
  
})

```
